language: node_js
node_js:
  - '10'

cache: yarn

install:
  - yarn

script:
  - yarn prebuild

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";

      docker build -t lynlab/luppiter:latest .;
      docker push lynlab/luppiter:latest;

      if [ -n "${TRAVIS_TAG}" ]; then
        docker build -t lynlab/luppiter:${TRAVIS_TAG} .;
        docker push lynlab/luppiter:${TRAVIS_TAG};
      fi
    fi
