language: node_js
node_js:
  - '10'

services:
  - postgresql

cache: yarn

install:
  - yarn
  - yarn global add codecov

before_script:
  - yarn build

  - psql -c 'create database luppiter_test;' -U postgres
  - yarn typeorm migration:run
  - yarn seed

script:
  - yarn lint
  - yarn test:all

after_success:
  - yarn coverage
  - codecov -f coverage/*.json

  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";

      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        docker build -t lynlab/luppiter:latest .;
        docker push lynlab/luppiter:latest;
      fi

      if [ -n "${TRAVIS_TAG}" ]; then
        docker build -t lynlab/luppiter:${TRAVIS_TAG} .;
        docker push lynlab/luppiter:${TRAVIS_TAG};
      fi
    fi
