name: Build and publish a docker image

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      run: |
        docker login --username hellodhlyn --password ${{ secrets.DOCKER_ACCESS_TOKEN }}

        docker build -t hellodhlyn/luppiter:latest .
        docker tag hellodhlyn/luppiter:latest hellodhlyn/luppiter:${GITHUB_REF##*/}

        docker push hellodhlyn/luppiter:latest
        docker push hellodhlyn/luppiter:${GITHUB_REF##*/}
